apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgers-storage
          persistentVolumeClaim:
              claimName: database-presistent-colume-claim
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: 
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
        volumeMounts:
          - name: postgers-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
